Premove
trevorbayless/cli-chess pull request #29
Opened 2024-05-21 03:57 UTC by LKL1235

premove function which https://github.com/trevorbayless/cli-chess/issues/27 discussed

2024-05-21 13:50 UTC, trevorbayless commented
Thanks for the PR! I haven't had time to look at it quite yet, but there are some [lint errors](https://github.com/trevorbayless/cli-chess/actions/runs/9168578213/job/25226917881?pr=29) that need to be addressed.

You can run `flake8` locally to verify you have fixed the errors. To do so, in your `venv` install cli-chess with `dev` dependencies by using the following command: `pip install -e .[dev]`. You should then navigate to `cli-chess/src/cli_chess` and run `flake8`.

2024-05-22 02:47 UTC, trevorbayless requested changes
Thanks again for the PR! I've added some comments to be addressed.

A couple additions to the review:
- The "PreMove" text is not appearing on online games.
- Premoves currently will kill an entire online game session if the pre-move is accepted but is then invalid after the opponent moves. Example: Starting as white, play e4 and premove e5. If the opponent plays e5 the game is then in a bad state. You should be able to replicate this easily in an online game against Stockfish. When quitting cli-chess after this happens, you will see exceptions in the console.

2024-05-22 02:47 UTC, trevorbayless commented on src/cli_chess/modules/premove/premove_view.py
> +        self.update(premove)
Unnecessary call to update in initialization

2024-05-22 02:47 UTC, trevorbayless commented on src/cli_chess/core/game/offline_game/offline_game_model.py
> +        if self.game_in_progress:
```suggestion
        if self.game_in_progress and not self.is_my_turn():
```

2024-05-22 02:47 UTC, trevorbayless commented on src/cli_chess/core/game/offline_game/offline_game_model.py
> +                    raise Warning("It is your turn, cant not make a premove")
Remove as this should not be hit.
```suggestion
                if self.is_my_turn():
                    raise Warning("It is your turn, cant not make a premove")
```

2024-05-22 03:43 UTC, LKL1235 commented
> Thanks again for the PR! I've added some comments to be addressed.
> 
> A couple additions to the review:
> 
> * The "PreMove" text is not appearing on online games.
> * Premoves currently will kill an entire online game session if the pre-move is accepted but is then invalid after the opponent moves. Example: Starting as white, play e4 and premove e5. If the opponent plays e5 the game is then in a bad state. You should be able to replicate this easily in an online game against Stockfish. When quitting cli-chess after this happens, you will see exceptions in the console.

Thanks for guide, I did fix them and commit

2024-05-22 12:40 UTC, trevorbayless approved these changes

2024-05-22 12:51 UTC, merged